---
title: Example with D3
author: James Laird-Smith
date: '2018-09-03'
slug: example-with-d3
categories: []
tags: []
header:
  caption: ''
  image: ''
summary: "Example using D3."
draft: false
---

```{r setup, echo=FALSE}
library(r2d3)
```


```{r echo=FALSE}
data <- c(4, 8, 15, 16, 23, 42)
```

```{d3 echo=FALSE, data=data}

// var totalWidth = document.getElementById("htmlwidget-1").offsetWidth

 var totalWidth = document.getElementsByTagName('body')[0].offsetWidth

// var width = totalWidth*1;

// var totalWidth = document.getElementsByClassName("r2d3 html-widget html-widget-static-bound")[0].offsetWidth

var width = Math.min(width, totalWidth*0.8);

// var chart = d3.select("").attr("id","chart")

// var totalWidth = document.getElementById("chart").offsetWidth

// var width = totalWidth*0.8;

svg.selectAll('rect')
  .data(data)
  .enter()
    .append('rect')
      .attr('width', function(d) { return d * 1; })
      .attr('height', '20px')
      .attr('y', function(d, i) { return i * 22; })
      .attr('fill', "blue");
      
var test = svg.append("g");

test.append('text')
  .text(width)
  .attr("y", height)
  .attr("x", width)
  .attr("text-anchor", "end");
```


```{r eval=FALSE, include=FALSE}
r2d3(data=c(0.3, 0.6, 0.8, 0.95, 0.40, 0.20), script = "extest.js")
```

